grid_size: [6, 10, 5] # The size of the 3D grid
start_positions: # The start positions of the drones inside the grid
  - [0, 5, 2]  
  
goal_positions: # The goal positions for each drone
  - [4, 3, 2]  

obstacle_cells: # The list of cells inside the grid that are considered obstacles
  - [2, 3, 2]

localize_cells:
  - [4, 4, 2]
  - [5, 4, 2]
  - [3, 4, 2]

change_altitude: False # Only operate in the XY-plane

# MDP model parameters
step_cost: -1.0
collision_penalty: -50.0
goal_reward: 100.0
discount_factor: 0.98
max_num_steps: 20 # The maximum number of steps before the problem terminates
goal_tol: 0.5
step_size: 1.0 # Travel distance of drones
process_noise_std: 0.1
